// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pnGoodsFieldNames          = builder.RawFieldNames(&PnGoods{})
	pnGoodsRows                = strings.Join(pnGoodsFieldNames, ",")
	pnGoodsRowsExpectAutoSet   = strings.Join(stringx.Remove(pnGoodsFieldNames, "`goods_id`", "`create_time`", "`update_time`"), ",")
	pnGoodsRowsWithPlaceHolder = strings.Join(stringx.Remove(pnGoodsFieldNames, "`goods_id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	pnGoodsModel interface {
		Insert(ctx context.Context, data *PnGoods) (sql.Result, error)
		FindOne(ctx context.Context, goodsId int64) (*PnGoods, error)
		Update(ctx context.Context, data *PnGoods) error
		Delete(ctx context.Context, goodsId int64) error
	}

	defaultPnGoodsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PnGoods struct {
		GoodsId           int64   `db:"goods_id"`            // 主键、自增
		SpuId             int64   `db:"spu_id"`              // 商品spu_id
		SkuId             int64   `db:"sku_id"`              // 商品sku_id
		ZySn              string  `db:"zy_sn"`               // 资源编码
		SkuSn             string  `db:"sku_sn"`              // 商品货号
		FinanceSn         string  `db:"finance_sn"`          // 财务编码
		GoodsName         string  `db:"goods_name"`          // 商品名称
		GoodsImg          string  `db:"goods_img"`           // 商品图片
		ZtPrice           float64 `db:"zt_price"`            // 中台成本价
		GoodsPrice        float64 `db:"goods_price"`         // 商品价格
		GoodsPriceSell    float64 `db:"goods_price_sell"`    // 商品售卖价格
		SetPriceType      int64   `db:"set_price_type"`      // 售价修改类型：1固定价格 2浮动倍率
		SetPriceRate      float64 `db:"set_price_rate"`      // 浮动倍率
		CurrCatId         int64   `db:"curr_cat_id"`         // 商品分类
		CatId             int64   `db:"cat_id"`              // 商品一级分类id
		SecondCatId       int64   `db:"second_cat_id"`       // 二级分类id
		ThirdCatId        int64   `db:"third_cat_id"`        // 三级分类id
		ZhongtaiCat       int64   `db:"zhongtai_cat"`        // 中台分类
		BrandId           int64   `db:"brand_id"`            // 商品品牌
		ZhongtaiBrand     int64   `db:"zhongtai_brand"`      // 中台品牌id
		UpdateTime        int64   `db:"update_time"`         // 修改时间
		AddTime           int64   `db:"add_time"`            // 添加时间
		IsGift            int64   `db:"is_gift"`             // 是否为礼包商品
		SupplierId        int64   `db:"supplier_id"`         // 供货商id
		Supplier          string  `db:"supplier"`            // 供货商别名
		SuppliersNameReal string  `db:"suppliers_name_real"` // 供货商 真实名称
		SaleCount         int64   `db:"sale_count"`          // 销量
		CompleteComDegree int64   `db:"complete_com_degree"` // 企业专区商品上下架
		OnSale            int64   `db:"on_sale"`             // 上下架状态 0：下架 1：上架
		IsVirtual         int64   `db:"is_virtual"`          // 是否虚拟卡 0：否 1：是
		IsMinPrice        int64   `db:"is_min_price"`        // 是否该spu下价格最低商品 0：否 1：是
		MinSaleCount      int64   `db:"min_sale_count"`      // 起售数量
		GoodsRestrictHour int64   `db:"goods_restrict_hour"` // 限制购买时间
		GoodsRestrictNum  int64   `db:"goods_restrict_num"`  // 限制购买数量
		GoodsStock        string  `db:"goods_stock"`         // 礼包库存
		IsShow            int64   `db:"is_show"`             // 商品是否显示 0：否 1：是
		SortTag           int64   `db:"sort_tag"`            // 商品列表搜索排序权重，值越高权重越大，商品越靠前
		IsShowSellout     int64   `db:"is_show_sellout"`     // 无货是否显示补货中 0：否 1：是
		IsRecommond       int64   `db:"is_recommond"`        // 是否推荐 0：否 1：是
		IsNew             int64   `db:"is_new"`              // 是否新品 0：否 1：是
		IsHot             int64   `db:"is_hot"`              // 是否热卖 0：否 1：是
		VirtualSkuType    int64   `db:"virtual_sku_type"`    // 虚拟电子券类型 0：普通电子券 1：嘉华 2：瑞幸 3：闹闹猴
	}
)

func newPnGoodsModel(conn sqlx.SqlConn) *defaultPnGoodsModel {
	return &defaultPnGoodsModel{
		conn:  conn,
		table: "`pn_goods`",
	}
}

func (m *defaultPnGoodsModel) Insert(ctx context.Context, data *PnGoods) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, pnGoodsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SpuId, data.SkuId, data.ZySn, data.SkuSn, data.FinanceSn, data.GoodsName, data.GoodsImg, data.ZtPrice, data.GoodsPrice, data.GoodsPriceSell, data.SetPriceType, data.SetPriceRate, data.CurrCatId, data.CatId, data.SecondCatId, data.ThirdCatId, data.ZhongtaiCat, data.BrandId, data.ZhongtaiBrand, data.AddTime, data.IsGift, data.SupplierId, data.Supplier, data.SuppliersNameReal, data.SaleCount, data.CompleteComDegree, data.OnSale, data.IsVirtual, data.IsMinPrice, data.MinSaleCount, data.GoodsRestrictHour, data.GoodsRestrictNum, data.GoodsStock, data.IsShow, data.SortTag, data.IsShowSellout, data.IsRecommond, data.IsNew, data.IsHot, data.VirtualSkuType)
	return ret, err
}

func (m *defaultPnGoodsModel) FindOne(ctx context.Context, goodsId int64) (*PnGoods, error) {
	query := fmt.Sprintf("select %s from %s where `goods_id` = ? limit 1", pnGoodsRows, m.table)
	var resp PnGoods
	err := m.conn.QueryRowCtx(ctx, &resp, query, goodsId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPnGoodsModel) Update(ctx context.Context, data *PnGoods) error {
	query := fmt.Sprintf("update %s set %s where `goods_id` = ?", m.table, pnGoodsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SpuId, data.SkuId, data.ZySn, data.SkuSn, data.FinanceSn, data.GoodsName, data.GoodsImg, data.ZtPrice, data.GoodsPrice, data.GoodsPriceSell, data.SetPriceType, data.SetPriceRate, data.CurrCatId, data.CatId, data.SecondCatId, data.ThirdCatId, data.ZhongtaiCat, data.BrandId, data.ZhongtaiBrand, data.AddTime, data.IsGift, data.SupplierId, data.Supplier, data.SuppliersNameReal, data.SaleCount, data.CompleteComDegree, data.OnSale, data.IsVirtual, data.IsMinPrice, data.MinSaleCount, data.GoodsRestrictHour, data.GoodsRestrictNum, data.GoodsStock, data.IsShow, data.SortTag, data.IsShowSellout, data.IsRecommond, data.IsNew, data.IsHot, data.VirtualSkuType, data.GoodsId)
	return err
}

func (m *defaultPnGoodsModel) Delete(ctx context.Context, goodsId int64) error {
	query := fmt.Sprintf("delete from %s where `goods_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, goodsId)
	return err
}

func (m *defaultPnGoodsModel) tableName() string {
	return m.table
}
