// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/kevwan/go-stash/stash/lib"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pnScenicFieldNames          = builder.RawFieldNames(&PnScenic{})
	pnScenicRows                = strings.Join(pnScenicFieldNames, ",")
	pnScenicRowsExpectAutoSet   = strings.Join(stringx.Remove(pnScenicFieldNames, "`scenic_id`", "`create_time`", "`update_time`"), ",")
	pnScenicRowsWithPlaceHolder = strings.Join(stringx.Remove(pnScenicFieldNames, "`scenic_id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	pnScenicModel interface {
		Insert(ctx context.Context, data *PnScenic) (sql.Result, error)
		FindOne(ctx context.Context, scenicId int64) (*PnScenic, error)
		FindOneById(ctx context.Context, id int64) (*PnScenic, error)
		Update(ctx context.Context, data *PnScenic) error
		Delete(ctx context.Context, scenicId int64) error
	}

	defaultPnScenicModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PnScenic struct {
		ScenicId         int64              `db:"scenic_id" json:"scenic_id,string"`         // 自增id
		Id               int64              `db:"id" json:"id,string"`                       // 景点id
		Name             string             `db:"name" json:"name,omitempty"`                   // 景点名称
		Address          string             `db:"address" json:"address,omitempty"`             // 景点地址
		CommentGrade     float64            `db:"comment_grade" json:"comment_grade,string"` // 点评分（满分 5 分，小数点后 1 位）
		PmrRecommand     string             `db:"pmr_recommand" json:"pmr_recommand,omitempty"` // 产品经理推荐；一般用来描述景点的特色
		Star             int64              `db:"star" json:"star,string"`                   // 景区星级（最高 5，即 5A）
		MarketPrice      float64            `db:"market_price" json:"market_price,string"`   // 市场价（人民币价格，精确至小数点后 2 位）
		Price            float64            `db:"price" json:"price,string"`                 // 分销价格（人民币价格，精确至小数点后 2 位）
		ThemeList        string             `db:"theme_list" json:"theme_list,omitempty"`       // 主题列表如：1,2,3
		IsValid          int64              `db:"is_valid" json:"is_valid,string"`           // 有效性（根据返回参数判断）
		CtripPrice       float64            `db:"ctrip_price" json:"ctrip_price,string"`     // 携程卖价（人民币价格，精确至小数点后 2 位）
		ImageUrl         string             `db:"image_url" json:"image_url,omitempty"`         // 景点首图链接
		ImgList          string             `db:"img_list" json:"img_list,omitempty"`           // 图片列表，调用图片接口
		Url              string             `db:"url" json:"url,omitempty"`                     // 景点详情页对应 URL
		OpenTimeDesc     string             `db:"open_time_desc" json:"open_time_desc,omitempty"`
		FirstBookingDate int64              `db:"first_booking_date" json:"first_booking_date,string"` // 最早可预订日期
		Longitude        float64            `db:"longitude" json:"longitude,string"`                   // 经度（数据取自高德） 精确到小数点后六位
		Latitude         float64            `db:"latitude" json:"latitude,string"`                     // 纬度（数据取自高德）精确到小数点后六位
		UpdateTime       int64              `db:"update_time" json:"update_time,string"`               // 更新时间
		IsShow           int64              `db:"is_show" json:"is_show,string"`                       // 是否显示
		RecommendSort    int64              `db:"recommend_sort" json:"recommend_sort,string"`         // 推荐排序
		CountryId        int64              `db:"country_id" json:"country_id,string"`                 // 国家id
		ProvinceId       int64              `db:"province_id" json:"province_id,string"`               // 省id
		CityId           int64              `db:"city_id" json:"city_id,string"`                       // 城市id
		CityEname        string             `db:"city_ename" json:"city_ename,omitempty"`                 // 城市拼音
		CityInfo         string             `db:"city_info" json:"city_info,omitempty"`                   // 城市信息
		InChina          int64              `db:"in_china" json:"in_china,string"`                     // 是否国内1:国内 2国外
		CityCode         int64              `db:"city_code" json:"city_code,string"`                   // 博弈城市id
		Test             lib.JsonNullString `db:"test" json:"test"`                                       // test
	}
)

func newPnScenicModel(conn sqlx.SqlConn) *defaultPnScenicModel {
	return &defaultPnScenicModel{
		conn:  conn,
		table: "`pn_scenic`",
	}
}

func (m *defaultPnScenicModel) Insert(ctx context.Context, data *PnScenic) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, pnScenicRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Address, data.CommentGrade, data.PmrRecommand, data.Star, data.MarketPrice, data.Price, data.ThemeList, data.IsValid, data.CtripPrice, data.ImageUrl, data.ImgList, data.Url, data.OpenTimeDesc, data.FirstBookingDate, data.Longitude, data.Latitude, data.IsShow, data.RecommendSort, data.CountryId, data.ProvinceId, data.CityId, data.CityEname, data.CityInfo, data.InChina, data.CityCode, data.Test)
	return ret, err
}

func (m *defaultPnScenicModel) FindOne(ctx context.Context, scenicId int64) (*PnScenic, error) {
	query := fmt.Sprintf("select %s from %s where `scenic_id` = ? limit 1", pnScenicRows, m.table)
	var resp PnScenic
	err := m.conn.QueryRowCtx(ctx, &resp, query, scenicId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPnScenicModel) FindOneById(ctx context.Context, id int64) (*PnScenic, error) {
	var resp PnScenic
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pnScenicRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPnScenicModel) Update(ctx context.Context, data *PnScenic) error {
	query := fmt.Sprintf("update %s set %s where `scenic_id` = ?", m.table, pnScenicRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.Address, data.CommentGrade, data.PmrRecommand, data.Star, data.MarketPrice, data.Price, data.ThemeList, data.IsValid, data.CtripPrice, data.ImageUrl, data.ImgList, data.Url, data.OpenTimeDesc, data.FirstBookingDate, data.Longitude, data.Latitude, data.IsShow, data.RecommendSort, data.CountryId, data.ProvinceId, data.CityId, data.CityEname, data.CityInfo, data.InChina, data.CityCode, data.Test, data.ScenicId)
	return err
}

func (m *defaultPnScenicModel) Delete(ctx context.Context, scenicId int64) error {
	query := fmt.Sprintf("delete from %s where `scenic_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, scenicId)
	return err
}

func (m *defaultPnScenicModel) tableName() string {
	return m.table
}
