Clusters:
- Input:
    Kafka:
      Name: gostash-pinuc
      Log:
        Mode: console   #[console,file,volume]
      Brokers:
        - "192.168.1.41:9092"
      Topics:
        - t_fx_100006
      Group: cg_fx_test
#      Consumers: 16
      Consumers: 1
      Processors: 1
      Conns: 1
      Offset: "first"
  Filters:
    - Action: drop
      Conditions:
        - Key: k8s_container_name
          Value: "-rpc"
          Type: contains
        - Key: level
          Value: info
          Type: match
          Op: and
    - Action: remove_field
      Fields:
        - message
        - _source
        - _type
        - _score
        - _id
        - "@version"
        - topic
        - index
        - beat
        - docker_container
        - offset
        - prospector
        - source
        - stream
    - Action: transfer
      Field: message
      Target: data
  Output:
    ElasticSearch:
      Hosts:
        - "http://192.168.1.41:9200"
     # Index: "{.event}-{{yyyy-MM-dd}}"
      Index: "{.event}"  #未用
      Username: "elastic"
      Password: "bCd2pBx6OcY5elfnj7aT"
      MaxChunkBytes: 5242880
      GracePeriod: 10s
      Compress: false
      TimeZone: UTC
  DB:
    MysqlConf:
      DataSource: "root:openthe*1*db@tcp(192.168.1.87:3306)/db_t_fenxiao?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"



