CREATE TABLE `pn_damai_order` (
                                  `order_id` int NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
                                  `user_id` int NOT NULL,
                                  `user_name` char(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '用户名（手机号）',
                                  `order_sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '订单号',
                                  `order_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT ' 0：待付款 1：已付款 2：已发货 3：已取消 4:未补差 5：已退款 6:已完成',
                                  `deliver_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '发货状态 0：未发货 1：已发货 2：已退货',
                                  `post_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '邮费',
                                  `total_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '商品总价',
                                  `total_base_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '订单商品成本总价',
                                  `pay_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额(商品总价+邮费)',
                                  `card_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付卡号',
                                  `card_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '卡类型  1：储值卡 2：次卡',
                                  `card_type_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '卡类型名称',
                                  `card_pay_price` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0.00' COMMENT '卡券支付金额',
                                  `card_pay_one_card` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '次卡支付金额',
                                  `card_response` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '卡消费返回信息',
                                  `order_time` int NOT NULL DEFAULT '0' COMMENT '订单时间',
                                  `pay_time` int NOT NULL DEFAULT '0' COMMENT '支付时间',
                                  `receiver` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收货人',
                                  `receiver_phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收货人手机号',
                                  `goods_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '商品名称',
                                  `goods_id` int NOT NULL DEFAULT '0' COMMENT '演出商品id',
                                  `sessions_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '场次名称',
                                  `sessions_id` int NOT NULL DEFAULT '0' COMMENT '场次id',
                                  `price_id` int NOT NULL DEFAULT '0' COMMENT '价格id',
                                  `seat_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '座位信息',
                                  `id_seat` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:未选座 1：选座',
                                  `damai_pay_result` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '大麦支付返回结果',
                                  `damai_order_sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '大麦订单号',
                                  `damai_order_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '大麦订单状态',
                                  `user_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '观影人信息',
                                  `start_time` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '演出时间',
                                  `delivery_types` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1和3为电子票，2和4为纸质票。',
                                  `pay_limit_time` int NOT NULL DEFAULT '0' COMMENT '过期时间',
                                  `num` int NOT NULL DEFAULT '1' COMMENT '数量',
                                  `pay_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '付款状态 0：待付款 1：已付款 2：未付款 3:支付失败 4:未补差价5：已完成',
                                  `is_hide` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:正常1：关闭',
                                  `wx_response` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '微信回调结果',
                                  `showImg` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '商品图片',
                                  `price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '单价',
                                  `venue_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '场馆名称',
                                  `venue_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '场馆地址',
                                  `city_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '城市名称',
                                  `wx_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '微信补差金额',
                                  `is_seat` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1:有座位信息 0：没有座位信息',
                                  `order_maizuo_sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '卖座订单号',
                                  `platform` tinyint(1) NOT NULL DEFAULT '2' COMMENT '1：pc 2:手机',
                                  PRIMARY KEY (`order_id`),
                                  FULLTEXT KEY `card` (`card_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1888 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci