CREATE TABLE `pn_damai_show` (
                                 `id` int NOT NULL AUTO_INCREMENT,
                                 `project_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '门票名称',
                                 `classify_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '一级分类名称',
                                 `city_id` int NOT NULL DEFAULT '0' COMMENT '城市id',
                                 `city_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '城市名称',
                                 `is_has_seat` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否有座： 0=无座 1=有座',
                                 `project_id` int NOT NULL DEFAULT '0' COMMENT '项目ID',
                                 `project_status` int NOT NULL DEFAULT '30' COMMENT '项目状态，0：创建中 10：已创建 20：待销售 30：销售中 40：项目取消 50：项目结束 60:定时开售，一般30之前的状态不会透出给渠道',
                                 `trader_id` int NOT NULL DEFAULT '0' COMMENT '主办方ID',
                                 `trader_name` varchar(255) NOT NULL DEFAULT '' COMMENT '主办方名称',
                                 `venue_id` int NOT NULL DEFAULT '0' COMMENT '场馆id',
                                 `lat` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0.00000' COMMENT '纬度',
                                 `lng` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0.00000' COMMENT '经度',
                                 `venue_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '场馆名称',
                                 `venue_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '场馆地址',
                                 `is_test` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否测试项目 0-正式项目 1-测试项目',
                                 `classify_id` int NOT NULL DEFAULT '0' COMMENT '一级分类id',
                                 `third_classify_name` varchar(255) NOT NULL DEFAULT '' COMMENT '二级分类名称',
                                 `third_classify_id` int DEFAULT '0' COMMENT '二级分类id',
                                 `on_sale` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1:上架：0：下架',
                                 `is_sale` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1:热销 0：普通',
                                 `add_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '添加时间',
                                 `delivery_types` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '取票类型1-无纸化,2-快递票,3-自助换票,4-门店自取。1、3属于电子票换票方式,2、4属于纸质票取票方式',
                                 `deposit_info` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '寄存说明',
                                 `purchase_limitation_once` int DEFAULT '1' COMMENT '项目单次限购数量',
                                 `real_name_notice` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '实名制购票',
                                 `show_detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '演出详情',
                                 `show_end_time` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '演出销售结束时间',
                                 `show_start_time` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '演出开售时间',
                                 `show_time` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '演出时间',
                                 `children_notice` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '儿童购票说明',
                                 `entrance_notice` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '入场说明',
                                 `limit_notice` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '	限购说明',
                                 `perform_time_detail_list` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '演出时间说明',
                                 `policy_of_return` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '退换政策',
                                 `prohibited_items` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '禁止携带物品说明',
                                 `classify_code` int DEFAULT '0' COMMENT '分类id',
                                 `show_pic` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '演出海报图',
                                 `choice_seat_notice` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '是否支持选座',
                                 `eticket_notice` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '	通过票夹中的二维码或身份证，可以直接验票入场（具体以下单后票夹信息为准）',
                                 `self_get_ticket_notice` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '	需要您在指定的取票地点取票，请在确认订单的时候仔细确认取票地址（具体以下单后票夹信息为准）',
                                 `artists` text COMMENT '艺人JSON',
                                 `ip_card` text COMMENT '品牌JSON',
                                 `post_city` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '发货城市',
                                 `pickup_address_list` text COMMENT '上门自取地址',
                                 PRIMARY KEY (`id`),
                                 KEY `id` (`id`) USING BTREE,
                                 KEY `project_id` (`project_id`) USING BTREE,
                                 KEY `project_name` (`project_name`) USING BTREE,
                                 KEY `city_id` (`city_id`) USING BTREE,
                                 KEY `show_pic` (`show_pic`) USING BTREE,
                                 KEY `city_name` (`city_name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10251 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci