CREATE TABLE `pn_kk_order` (
                               `order_id` int NOT NULL AUTO_INCREMENT,
                               `user_id` int NOT NULL DEFAULT '0' COMMENT '用户id',
                               `user_name` char(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '用户名手机号',
                               `order_sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '订单号',
                               `pay_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '付款状态 0：待付款 1：已付款 2:支付失败 3:未补差价4:已取消5:已退款6：已完成',
                               `regdate` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '预约日期',
                               `package_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '套餐编号',
                               `hospId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '医院编号',
                               `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '体检人姓名',
                               `sex` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1，性别1男，2女，当套餐性别不为0时',
                               `married` tinyint NOT NULL DEFAULT '1' COMMENT '如：1，1已婚，0未婚；',
                               `contactTel` char(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '联系电话',
                               `cardNumber` char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '证件号码',
                               `cardType` tinyint(1) NOT NULL DEFAULT '1' COMMENT '证件类型',
                               `onlyNum` int NOT NULL DEFAULT '0' COMMENT '第三方唯一编码',
                               `payType` tinyint(1) NOT NULL DEFAULT '1' COMMENT '支付方式；如1，当机构支付方式不为2时，必须与机构的支付方式相对应，1在线支付，0线下支付',
                               `total_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '商品总价',
                               `card_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付卡号',
                               `card_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '卡类型  1：储值卡 2：次卡',
                               `card_type_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '卡类型名称',
                               `card_pay_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '卡券支付金额（积分金额）',
                               `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '附言',
                               `order_time` int NOT NULL DEFAULT '0' COMMENT '订单时间',
                               `pay_time` int NOT NULL DEFAULT '0' COMMENT '支付时间',
                               `order_extend_snapshot` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订单其他信息快照（商品分组信息、商品价、邮费、总计等）',
                               `pay_limit_time` int NOT NULL DEFAULT '0' COMMENT '未支付过期时间',
                               `wx_response` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '微信回调结果',
                               `is_show` tinyint(1) NOT NULL DEFAULT '1' COMMENT '订单是否显示 0：否 1：是',
                               `platform` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单平台  1：PC   2：手机',
                               `packageName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '套餐名称',
                               `hospName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '机构名称',
                               `wx_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '微信支付金额',
                               `card_response` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '支付返回结果',
                               `order_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1:预约中2：预约成功 3：预约失败 4：退款处理中 5：退款成功（已退款） 6、已完成 8、已关闭',
                               `orderId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '康康订单号id',
                               `k_response` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '康康回调',
                               `k_time` int NOT NULL DEFAULT '0',
                               `total_base_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '成本价格',
                               `sms_log` varchar(255) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '短信信息',
                               `thirdNum` varchar(100) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '康康订单',
                               PRIMARY KEY (`order_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=435 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC