CREATE TABLE `pn_kk_setmeal` (
                                 `id` int NOT NULL AUTO_INCREMENT,
                                 `packageCat` text COMMENT '套餐大类别',
                                 `isKKTC` tinyint(1) DEFAULT NULL COMMENT '是否为康康套餐',
                                 `packageId` int NOT NULL DEFAULT '0' COMMENT '套餐ID',
                                 `packageName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '套餐名称',
                                 `packageCode` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '套餐编号',
                                 `hospId` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '医院编号',
                                 `originalPrice` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT 'kk成本',
                                 `packageImage` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
                                 `packageType` text COMMENT '套餐小类型',
                                 `packageCityName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '城市名称',
                                 `packageCityCode` int DEFAULT '0' COMMENT '城市id',
                                 `packageAreaName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '区名称',
                                 `packageAreaCode` int DEFAULT '0' COMMENT '区id',
                                 `packageSex` tinyint(1) DEFAULT '0' COMMENT '套餐性别 1男，2女0通用',
                                 `payType` int DEFAULT '0' COMMENT '支付类型（1在线支付，0线下支付，2同时支持在线和线下）',
                                 `attention` text COMMENT '注意事项',
                                 `jcyy` text COMMENT '检查意义',
                                 `tchyzt` tinyint(1) NOT NULL DEFAULT '2' COMMENT '预约可选婚姻状态(0，已婚  1，未婚 2，不限)',
                                 `on_sale` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1:上架 0：下架',
                                 `sort` int NOT NULL DEFAULT '1' COMMENT '排序',
                                 `manPrice` decimal(10,0) NOT NULL DEFAULT '0' COMMENT '男性价格',
                                 `womanPrice` decimal(10,0) NOT NULL DEFAULT '0' COMMENT '女性价格',
                                 `womanMarryPrice` decimal(10,0) NOT NULL DEFAULT '0' COMMENT '女性已婚价格',
                                 `is_kangkang` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1:是 0:否',
                                 `price` decimal(10,2) DEFAULT '0.00' COMMENT '售价',
                                 `kkzk` decimal(10,2) DEFAULT NULL,
                                 `c_manPrice` decimal(10,0) NOT NULL DEFAULT '0' COMMENT '男性成本价格',
                                 `c_womanPrice` decimal(10,0) NOT NULL DEFAULT '0' COMMENT '女性成本价格',
                                 `c_womanMarryPrice` decimal(10,0) NOT NULL DEFAULT '0' COMMENT '女性已婚成本价格',
                                 `isOnline` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1，上线，0下线',
                                 `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                 `shelf_time` int NOT NULL DEFAULT '0' COMMENT '上架时间',
                                 `off_shelf_time` int NOT NULL DEFAULT '0' COMMENT '下架时间',
                                 `cb_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '成本价',
                                 PRIMARY KEY (`id`),
                                 KEY `id` (`id`) USING BTREE,
                                 KEY `hospId` (`hospId`) USING BTREE,
                                 KEY `packageCode` (`packageCode`) USING BTREE,
                                 KEY `packageId` (`packageId`) USING BTREE,
                                 KEY `packageCityName` (`packageCityName`) USING BTREE,
                                 KEY `packageAreaName` (`packageAreaName`) USING BTREE,
                                 KEY `packageAreaCode` (`packageAreaCode`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3273 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci