CREATE TABLE `pn_m_cinema` (
                               `id` int NOT NULL AUTO_INCREMENT,
                               `cinemaName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影院名称',
                               `cityName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '城市名称',
                               `cinemaId` int NOT NULL DEFAULT '0' COMMENT '影院id',
                               `seatFlag` int NOT NULL DEFAULT '0' COMMENT '是否支持订座票  0：不支持 1：支持',
                               `region` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '所在区',
                               `logo` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影院Logo图片',
                               `phone` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影院联系电话',
                               `busPath` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '公交线路',
                               `cityId` int NOT NULL DEFAULT '0' COMMENT '城市id',
                               `seatCounts` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影院每个厅含座位数，多个用-分隔；未知数量为0',
                               `hallId` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影院所含厅ID列表,多个厅用-分隔',
                               `hallNames` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '影院厅名称列表，多个用-分隔',
                               `atmPosition` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '取票机',
                               `businessCircle` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商圈',
                               `subway` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '地铁',
                               `address` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影院地址',
                               `ticketFlag` int NOT NULL DEFAULT '0' COMMENT '是否支持电子票  0：不支持 1：支持',
                               `longitude` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '径度',
                               `latitude` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '纬度',
                               `vipflags` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影院所在厅是否为VIP厅，多个用-分隔，0表示非VIP，1为vip',
                               `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                               `are2D_price` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '2D抵扣价',
                               `are3D_price` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '3D抵扣价',
                               `online_consum` tinyint(1) NOT NULL DEFAULT '0' COMMENT '线上是否支持购买',
                               `province_search` int NOT NULL DEFAULT '0' COMMENT '省id  卡查询使用',
                               `city_search` int NOT NULL DEFAULT '0' COMMENT '市id  卡查询使用',
                               `area_search` int NOT NULL DEFAULT '0' COMMENT '区id   卡查询',
                               `glasses` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否提供3d眼镜',
                               `by_cityId` int NOT NULL DEFAULT '0' COMMENT '博影城市id',
                               `online_show` tinyint(1) NOT NULL DEFAULT '1' COMMENT '线上是否显示',
                               `price_multiple` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '此影院下排期倍数',
                               `price_base` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '此影院下排期基数',
                               `time_cinema_id` int unsigned DEFAULT '0',
                               `code` tinyint(1) NOT NULL DEFAULT '1' COMMENT '标识',
                               `local_cinema` int NOT NULL DEFAULT '0' COMMENT '匹配影院id',
                               `zz_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '专资编码 ',
                               PRIMARY KEY (`id`) USING BTREE,
                               UNIQUE KEY `cinemaId` (`cinemaId`) USING BTREE,
                               KEY `city_index` (`cityId`) USING BTREE,
                               KEY `region_index` (`region`) USING BTREE,
                               KEY `cinema` (`cinemaName`) USING BTREE,
                               KEY `indexSearch` (`cinemaName`,`phone`,`address`,`cinemaId`) USING BTREE,
                               KEY `by_city` (`by_cityId`) USING BTREE,
                               KEY `online_show` (`online_show`) USING BTREE,
                               KEY `time_cinema_id` (`time_cinema_id`) USING BTREE,
                               KEY `idx_zzcode` (`zz_code`) USING BTREE,
                               KEY `idx_localcinema` (`local_cinema`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1199708 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='影院列表'