CREATE TABLE `pn_m_films` (
                              `id` int NOT NULL AUTO_INCREMENT,
                              `filmsId` int NOT NULL DEFAULT '0' COMMENT '影片id',
                              `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '电影名',
                              `osPicAddr` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'os远程图片',
                              `picAddr` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '图片地址 ',
                              `videoUrl` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '电影预告片Id ',
                              `shortInfo` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '电影一句话简介',
                              `dimensional` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '电影维度类型： 例如：2D 3D IMAX',
                              `type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影片类型，多个名字使用| 分隔类型：可为空',
                              `director` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '导演，多个名字使用| 分隔 类型可为空',
                              `info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '电影描述，包含HTML格式数据类型',
                              `releaseDate` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '电影首映日期',
                              `area` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '国家地区，多个名字使用|',
                              `company` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '发行公司',
                              `length` int NOT NULL DEFAULT '0' COMMENT '片长，以分钟为单位类型',
                              `grade` decimal(10,1) NOT NULL DEFAULT '0.0' COMMENT '电影评分',
                              `actors` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '主演，多个名字使用| ',
                              `saleCount` int NOT NULL DEFAULT '0' COMMENT '销售数量',
                              `language` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '语言，多个名字使用| 分隔类型可为空',
                              `isShow` int NOT NULL DEFAULT '0' COMMENT '1：正在上映，2：即将上映',
                              `isrecommend` int NOT NULL DEFAULT '0' COMMENT '是否推荐 1：推荐 2：不推荐',
                              `recommendimg` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '推荐图',
                              `deasc` int NOT NULL DEFAULT '999',
                              `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                              `desc_count` int NOT NULL DEFAULT '0',
                              `localfilm` int NOT NULL DEFAULT '0' COMMENT '本地匹配字段',
                              `code` tinyint(1) DEFAULT '1' COMMENT '标识',
                              `unionCode` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '广电总局统一编码',
                              `add_time` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '添加时间',
                              PRIMARY KEY (`id`),
                              UNIQUE KEY `id` (`id`) USING BTREE,
                              UNIQUE KEY `filmsId` (`filmsId`) USING BTREE,
                              KEY `deanddate` (`releaseDate`,`deasc`) USING BTREE,
                              KEY `is_s_index` (`isShow`) USING BTREE,
                              KEY `name` (`name`) USING BTREE,
                              KEY `ordercount` (`desc_count`) USING BTREE,
                              KEY `idx_localfilm` (`localfilm`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10453 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='电影表'