CREATE TABLE `pn_m_order` (
                              `id` int NOT NULL AUTO_INCREMENT,
                              `orderId` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
                              `userId` int NOT NULL DEFAULT '0' COMMENT '用户id',
                              `userName` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
                              `sendMobile` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
                              `filmId` int NOT NULL DEFAULT '0' COMMENT '电影id',
                              `filmsName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '电影名',
                              `dimensional` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '电影类型',
                              `cinemaId` int NOT NULL DEFAULT '0' COMMENT '影院id',
                              `cinemaName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '影院名',
                              `cityId` int DEFAULT NULL,
                              `filmImg` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '电影图片',
                              `seatName` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '座位名',
                              `seatIds` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '座位',
                              `amount` tinyint NOT NULL DEFAULT '0' COMMENT '票张数',
                              `price` smallint NOT NULL DEFAULT '0' COMMENT '售价',
                              `orprice` smallint NOT NULL DEFAULT '0' COMMENT '原价',
                              `total` smallint NOT NULL DEFAULT '0' COMMENT '总价',
                              `orderStatus` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '0：未付款  1：已付款  2：已扣点未补差价  3：已退款（退卡退差价） 4：已退款（退卡未退差价）5:已取消   6:已确认(第三方收到订单)   7: 已发码  8：已完成(虚拟，不存在) 9.退款失败10.出票失败',
                              `orderTime` int NOT NULL DEFAULT '0' COMMENT '订单提交时间',
                              `sendMsg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '短信发送信息',
                              `payCardNum` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
                              `payCardSport` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付点数/次数',
                              `payCardType` tinyint(1) NOT NULL DEFAULT '0' COMMENT '卡类型',
                              `payCardMoney` decimal(10,2) DEFAULT '0.00',
                              `payCardName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '卡名称',
                              `confirmId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '确认id',
                              `offerOrderId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '序列号',
                              `thirdConfirmId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '验证码',
                              `atm` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '取票方式',
                              `sendStatus` tinyint(1) NOT NULL DEFAULT '0' COMMENT '信息发送状态 0：未发送  1：短信发送   2：微信发送 3：失败信息发送',
                              `Platform` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0：PC  1：手机',
                              `isSpecial` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否是特价票1:是,0:不是',
                              `wxRefund` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '微信退款',
                              `wx_response` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '微信回调信息',
                              `openId` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '微信opendid',
                              `foretellsData` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '排期信息',
                              `surplusMoney` decimal(10,2) DEFAULT '0.00',
                              `realInfo` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '观影人信息',
                              `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                              `is_hide` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否隐藏  1：隐藏   ',
                              `orderMaizuoSn` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '卖座订单号',
                              `timeOrderId` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '时光网主id',
                              `timeSubOrderId` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '时光网子id',
                              `erHyi` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否二换一',
                              `apiOrderSn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '接口订单号',
                              `zyOrderSn` varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '三方资源订单号',
                              `orderType` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单类型 0:卖座 1:时光  2:品诺卖座3：影托邦，4：淘票票，5：时光，6：鼎新',
                              PRIMARY KEY (`id`),
                              UNIQUE KEY `orderid` (`orderId`) USING BTREE,
                              KEY `timeOrderId` (`timeOrderId`),
                              KEY `timeSubOrderId` (`timeSubOrderId`),
                              KEY `idx_apiOrderSn` (`apiOrderSn`) USING BTREE,
                              FULLTEXT KEY `card` (`payCardNum`)
) ENGINE=InnoDB AUTO_INCREMENT=5582767 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci