CREATE TABLE `pn_order` (
                            `order_id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '主键，自增',
                            `user_id` int NOT NULL DEFAULT '0' COMMENT '用户id',
                            `user_name` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
                            `order_sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '订单号',
                            `parent_order_sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '父订单号，订单为子订单时该字段有值',
                            `order_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0：父订单 1：子订单',
                            `zt_order_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '中台订单号',
                            `order_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT ' 0：待付款 1：已付款 2：已发货 3：已取消 4:退款中 5：已退款 6:已完成 7:支付失败',
                            `pay_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '付款状态 0：待付款 1：已付款 2：未付款 3:支付失败 4:未补差价',
                            `deliver_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '发货状态 0：未发货 1：已发货 2：已退货',
                            `pay_type` tinyint(1) NOT NULL DEFAULT '-1' COMMENT '支付方式  0 微信 1支付宝',
                            `post_fee` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '邮费',
                            `total_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '商品总价',
                            `total_base_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '总成本',
                            `refund_base_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '已退成本',
                            `pay_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额(商品总价+邮费)',
                            `card_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '支付卡号',
                            `card_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '卡类型  1：  红卡 2：蓝卡 3：绿卡',
                            `card_type_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '卡类型名称',
                            `card_pay_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '卡券支付金额',
                            `card_pay_one_card` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '次卡支付金额',
                            `card_response` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '卡消费返回信息',
                            `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '附言',
                            `order_time` int NOT NULL DEFAULT '0' COMMENT '订单时间',
                            `pay_time` int unsigned NOT NULL DEFAULT '0' COMMENT '支付时间',
                            `receiver` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收货人',
                            `receiver_phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收货人手机号',
                            `order_snapshot` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品快照',
                            `order_extend_snapshot` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '订单其他信息快照（商品分组信息、商品价、邮费、总计等）',
                            `receiver_snapshot` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '收货信息快照',
                            `zt_response` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '中台接口响应信息',
                            `pay_limit_time` int NOT NULL DEFAULT '0' COMMENT '未支付过期时间',
                            `wx_response` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '微信回调结果',
                            `express` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '快递名称',
                            `express_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '快递单号',
                            `is_show` tinyint(1) NOT NULL DEFAULT '1' COMMENT '订单是否显示 (拆单时，父订单此字段为0) 0：否 1：是 ',
                            `supplier_id` int NOT NULL DEFAULT '0' COMMENT '供应商id',
                            `supplier` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '供应商',
                            `is_gift` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否礼包订单 0：否 1：是',
                            `company_user_id` tinyint(1) NOT NULL DEFAULT '0' COMMENT '企业专区用户id 0:  商城 1：企业专区 2：次卡专区',
                            `companyde_goods_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '次卡专区礼包名',
                            `skus_name` varchar(3000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '订单商品名',
                            `platform` int NOT NULL DEFAULT '0' COMMENT '订单平台  1：PC   2：手机',
                            `company_goods_id` int NOT NULL DEFAULT '0' COMMENT '企业专区套餐id',
                            `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                            `is_hide` int NOT NULL DEFAULT '0' COMMENT '是否被删除',
                            `price_difference` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '微信补差金额（废弃）',
                            `price_difference_back` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '微信补差金额备份（废弃）',
                            `orderMaizuoSn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '卖座订单号',
                            `surplusMoney` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '微信补差金额',
                            `pay_serial_no` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '第三方支付流水号',
                            PRIMARY KEY (`order_id`) USING BTREE,
                            KEY `idx_cardno` (`card_no`) USING BTREE,
                            KEY `idx_ordertime` (`order_time`) USING BTREE,
                            KEY `idx_username` (`user_name`) USING BTREE,
                            KEY `idx_ordersn` (`order_sn`) USING BTREE,
                            KEY `idx_paytime` (`pay_time`) USING BTREE,
                            KEY `idx_parentordersn` (`parent_order_sn`) USING BTREE,
                            KEY `idx_supplierid` (`supplier_id`) USING BTREE,
                            KEY `idx_supplier` (`supplier`) USING BTREE,
                            KEY `idx_user_id` (`user_id`) USING BTREE,
                            KEY `idx_zt_order_id` (`zt_order_id`) USING BTREE,
                            KEY `idx_order_status` (`order_status`) USING BTREE,
                            KEY `idx_receiver` (`receiver`) USING BTREE,
                            FULLTEXT KEY `card` (`card_no`)
) ENGINE=InnoDB AUTO_INCREMENT=2144172 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='商品订单记录'