CREATE TABLE `pn_order_goods` (
                                  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
                                  `order_sn` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '子订单号',
                                  `order_sn_skuid` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '子订单号+商品id',
                                  `supplier_id` int NOT NULL DEFAULT '0' COMMENT '供应商id',
                                  `supplier` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '供应商名称',
                                  `goods_id` int NOT NULL DEFAULT '0' COMMENT '商品表主键id',
                                  `sku_id` int NOT NULL DEFAULT '0' COMMENT '商品skuId',
                                  `goods_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商品名',
                                  `goods_img` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商品主图',
                                  `zy_sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '资源编码',
                                  `sku_sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '货号',
                                  `finance_sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '财务编码',
                                  `brand_id` int NOT NULL DEFAULT '0' COMMENT '品牌id',
                                  `cate_id` int NOT NULL DEFAULT '0' COMMENT '分类id',
                                  `first_cat_id` int NOT NULL DEFAULT '0' COMMENT '商品一级分类id',
                                  `second_cat_id` int NOT NULL DEFAULT '0' COMMENT '商品二级分类id',
                                  `count` int NOT NULL DEFAULT '0' COMMENT '购买数量',
                                  `zt_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '中台成本价',
                                  `base_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '品诺对接中台结算价',
                                  `price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '品诺售价',
                                  `skuattr` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商品属性信息，json',
                                  `cake_time` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '蛋糕配送时间',
                                  `is_virtual` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否虚拟商品 0:否 1：是',
                                  `subgoods` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '配件信息,json',
                                  `virtual_code` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '虚拟卡号密码信息',
                                  `gifts` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '赠品',
                                  `refund_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '退款状态，0：未退 1：部分退 2：全部退',
                                  `refund_num` smallint NOT NULL DEFAULT '0' COMMENT '已退数量',
                                  `is_apply_refund` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否申请退款中 0：否 1：是',
                                  PRIMARY KEY (`id`) USING BTREE,
                                  KEY `idx_ordersn` (`order_sn`) USING BTREE,
                                  KEY `idx_ordersnskuid` (`order_sn_skuid`) USING BTREE,
                                  KEY `idx_supplierid` (`supplier_id`) USING BTREE,
                                  KEY `idx_skuid` (`sku_id`) USING BTREE,
                                  KEY `idx_cateid` (`first_cat_id`,`second_cat_id`,`cate_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2077765 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='订单商品快照表'