CREATE TABLE `pn_scenic` (
                             `scenic_id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
                             `id` int unsigned NOT NULL COMMENT '景点id',
                             `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '景点名称',
                             `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '景点地址',
                             `comment_grade` decimal(5,1) NOT NULL DEFAULT '0.0' COMMENT '点评分（满分 5 分，小数点后 1 位）',
                             `pmr_recommand` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '产品经理推荐；一般用来描述景点的特色',
                             `star` int unsigned NOT NULL COMMENT '景区星级（最高 5，即 5A）',
                             `market_price` decimal(10,2) NOT NULL COMMENT '市场价（人民币价格，精确至小数点后 2 位）',
                             `price` decimal(10,2) NOT NULL COMMENT '分销价格（人民币价格，精确至小数点后 2 位）',
                             `theme_list` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '主题列表如：1,2,3',
                             `is_valid` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '有效性（根据返回参数判断）',
                             `ctrip_price` decimal(10,2) NOT NULL COMMENT '携程卖价（人民币价格，精确至小数点后 2 位）',
                             `image_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '景点首图链接',
                             `img_list` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '图片列表，调用图片接口',
                             `url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '景点详情页对应 URL',
                             `open_time_desc` mediumtext NOT NULL,
                             `first_booking_date` int unsigned NOT NULL COMMENT '最早可预订日期',
                             `longitude` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '经度（数据取自高德） 精确到小数点后六位',
                             `latitude` decimal(10,6) NOT NULL DEFAULT '0.000000' COMMENT '纬度（数据取自高德）精确到小数点后六位',
                             `update_time` int NOT NULL DEFAULT '0' COMMENT '更新时间',
                             `is_show` tinyint(1) unsigned zerofill NOT NULL DEFAULT '1' COMMENT '是否显示',
                             `recommend_sort` int unsigned NOT NULL DEFAULT '0' COMMENT '推荐排序',
                             `country_id` int unsigned NOT NULL DEFAULT '0' COMMENT '国家id',
                             `province_id` int unsigned NOT NULL DEFAULT '0' COMMENT '省id',
                             `city_id` int NOT NULL DEFAULT '0' COMMENT '城市id',
                             `city_ename` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '城市拼音',
                             `city_info` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '城市信息',
                             `in_china` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否国内1:国内 2国外',
                             `city_code` int NOT NULL COMMENT '博弈城市id',
                             `test` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'test',
                             PRIMARY KEY (`scenic_id`),
                             UNIQUE KEY `uni_id` (`id`) COMMENT '景点id',
                             KEY `idx_recommend` (`recommend_sort`) USING BTREE,
                             KEY `idx_price` (`market_price`) USING BTREE,
                             KEY `uni_city_valid_show` (`city_id`,`is_valid`,`is_show`) USING BTREE,
                             KEY `idx_theme` (`theme_list`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1119336 DEFAULT CHARSET=utf8